Update hal_conf_extra.h
Prevent "redefinition of symbol" warning

When using DaisyDuino w/ PlatformIO, the [guidance on the forum](https://forum.electro-smith.com/t/daisy-seed-arduino-development-in-vscode/3639/2) instructs us to add the build flag `-D HAL_SDRAM_MODULE_ENABLED`. Without this, the program will not link due to an `undefined reference to 'HAL_SDRAM_Init'` error.

However, by manually defining the symbol, when we compile we see many "warning symbol redefined" errors. This `ifndef` guard quiets those warnings.

It would probably be better to resolve the issue that requires us to manually define `HAL_SDRAM_MODULE_ENABLED` - what is `HAL_SDRAM_Init` and why is it missing? Unfortunately, this is deeper into the daisy source code that I'm comfortable going.